name: PR_review

on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}
          
          echo "Review State: ${{ github.event.review.state }}"
          echo "Review Body: ${{ github.event.review.body }}"
          echo "Review Changes: ${{ toJson(github.event.changes) }}"

          PR_NUMBER="${{ github.event.pull_request.number }}"
          REVIEW_ID="${{ github.event.review.id }}"
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews/${REVIEW_ID}/comments"

          echo $PR_NUMBER
          echo $REVIEW_ID
          echo $COMMENT_URL
